import { Game, Player } from "../types/database";
import { characters } from "./characters";

export const players: Record<number, Player> = {
  0: new Player(
    0,
    characters[0],
    Game.IEGOCS,
    {
      GP: 153,
      TP: 144,
      Kick: 121,
      Dribbling: 154,
      Block: 111,
      Catch: 88,
      Technique: 102,
      Speed: 109,
      Stamina: 107,
      Lucky: 116,
      Freedom: 55,
    },
    "kid",
    [],
    "wind",
    "MF"
  ),
  1: new Player(
    1,
    characters[1],
    Game.IEGOCS,
    {
      GP: 153,
      TP: 144,
      Kick: 169,
      Dribbling: 119,
      Block: 102,
      Catch: 66,
      Technique: 126,
      Speed: 107,
      Stamina: 112,
      Lucky: 109,
      Freedom: 51,
    },
    "kid",
    [],
    "fire",
    "FW"
  ),
  2: new Player(
    2,
    characters[2],
    Game.IEGOCS,
    {
      GP: 144,
      TP: 147,
      Kick: 55,
      Dribbling: 71,
      Block: 95,
      Catch: 138,
      Technique: 107,
      Speed: 100,
      Stamina: 78,
      Lucky: 83,
      Freedom: 99,
    },
    "kid",
    [],
    "fire",
    "GK"
  ),
  3: new Player(
    3,
    characters[3],
    Game.IEGOCS,
    {
      GP: 147,
      TP: 142,
      Kick: 66,
      Dribbling: 75,
      Block: 117,
      Catch: 71,
      Technique: 100,
      Speed: 92,
      Stamina: 95,
      Lucky: 83,
      Freedom: 70,
    },
    "kid",
    [],
    "fire",
    "DF"
  ),
  4: new Player(
    4,
    characters[4],
    Game.IEGOCS,
    {
      GP: 130,
      TP: 142,
      Kick: 66,
      Dribbling: 90,
      Block: 141,
      Catch: 50,
      Technique: 116,
      Speed: 119,
      Stamina: 88,
      Lucky: 102,
      Freedom: 85,
    },
    "kid",
    [],
    "wood",
    "DF"
  ),
  5: new Player(
    5,
    characters[5],
    Game.IEGOCS,
    {
      GP: 147,
      TP: 124,
      Kick: 83,
      Dribbling: 83,
      Block: 146,
      Catch: 54,
      Technique: 112,
      Speed: 68,
      Stamina: 107,
      Lucky: 107,
      Freedom: 95,
    },
    "kid",
    [],
    "earth",
    "DF"
  ),
  6: new Player(
    6,
    characters[6],
    Game.IEGOCS,
    {
      GP: 136,
      TP: 149,
      Kick: 62,
      Dribbling: 85,
      Block: 116,
      Catch: 136,
      Technique: 109,
      Speed: 112,
      Stamina: 107,
      Lucky: 85,
      Freedom: 88,
    },
    "kid",
    [],
    "earth",
    "GK"
  ),
};
