import {
  // Affinity,
  // Game,
  // MoveCharacteristic,
  // MoveType,
  Spirit,
} from "../types/database";

export const spirits: Record<number, Spirit> = {
  // 1: new Spirit(
  //   1,
  //   "Lancelot",
  //   Game.IEGOCS,
  //   Affinity.fire,
  //   { FSP: 180, Attack: 50 },
  //   "Lancelot Lunge",
  //   Affinity.fire,
  //   MoveType.shoot,
  //   50,
  //   "Fire's Call",
  //   "Fire special moves become more effective for the whole team"
  // ),
  // 2: new Spirit(
  //   2,
  //   "Maestro",
  //   Game.IEGOCS,
  //   Affinity.wood,
  //   { FSP: 210, Attack: 20 },
  //   "Atomic Harmonic",
  //   Affinity.wood,
  //   MoveType.shoot,
  //   50,
  //   "Wood's Call",
  //   "Wood special moves become more effective for the whole team"
  // ),
  // 4: new Spirit(
  //   4,
  //   "Musashi",
  //   Game.IEGOCS,
  //   Affinity.earth,
  //   { FSP: 140, Attack: 100 },
  //   "Bushin Blades",
  //   Affinity.earth,
  //   MoveType.shoot,
  //   70,
  //   "Earth's Call",
  //   "Earth special moves become more effective for the whole team"
  // ),
  // 8: new Spirit(
  //   8,
  //   "Scramjet",
  //   Game.IEGOCS,
  //   Affinity.wind,
  //   { FSP: 120, Attack: 50 },
  //   "Hyperdrive",
  //   Affinity.wind,
  //   MoveType.dribble,
  //   40,
  //   "Ignition On",
  //   "All teammates sprint faster to catch up opponents on the pitch"
  // ),
  // 24: new Spirit(
  //   24,
  //   "Atlas",
  //   Game.IEGOCS,
  //   Affinity.earth,
  //   { FSP: 170, Attack: 110 },
  //   "Majin the Hand",
  //   Affinity.earth,
  //   MoveType.catch,
  //   80,
  //   "Technique Force X",
  //   "Raises the technique stat for all teammates by 30"
  // ),
  // 32: new Spirit(
  //   32,
  //   "Arch Pegasus",
  //   Game.IEGOCS,
  //   Affinity.wind,
  //   { FSP: 170, Attack: 80 },
  //   "Pegasus Punch",
  //   Affinity.wind,
  //   MoveType.shoot,
  //   95,
  //   "Dribble Force X",
  //   "Raises the dribble stat for all teammates by 30"
  // ),
  // 42: new Spirit(
  //   42,
  //   "Behemoth",
  //   Game.IEGOCS,
  //   Affinity.earth,
  //   { FSP: 130, Attack: 50 },
  //   "Titanic Shield",
  //   Affinity.wind,
  //   MoveType.catch,
  //   40,
  //   "Stage Presence",
  //   "Players with this spirit gain more power the more L-build allies they have",
  //   MoveCharacteristic.punch
  // ),
  // 50: new Spirit(
  //   50,
  //   "Majin",
  //   Game.IEGOCS,
  //   Affinity.earth,
  //   { FSP: 150, Attack: 50 },
  //   "Majin te Great",
  //   Affinity.earth,
  //   MoveType.catch,
  //   90,
  //   "Stamina Force X",
  //   "Raises the stamina stat for all teammates by 30"
  // ),
  // 53: new Spirit(
  //   53,
  //   "Pendragon",
  //   Game.IEGOCS,
  //   Affinity.neutral,
  //   { FSP: 150, Attack: 110 },
  //   "Dark Reaver",
  //   Affinity.neutral,
  //   MoveType.shoot,
  //   80,
  //   "Nobody's Call",
  //   "Non-elemental special moves become more effective for the whole team"
  // ),
  // 54: new Spirit(
  //   54,
  //   "Feng-Huang",
  //   Game.IEGOCS,
  //   Affinity.fire,
  //   { FSP: 150, Attack: 50 },
  //   "Firebird Flight",
  //   Affinity.fire,
  //   MoveType.shoot,
  //   50,
  //   "Pass Boost",
  //   "All teammates' passes are a little faster than normal"
  // ),
  // 56: new Spirit(
  //   56,
  //   "Athene",
  //   Game.IEGOCS,
  //   Affinity.wind,
  //   { FSP: 150, Attack: 50 },
  //   "Athenian Assault",
  //   Affinity.wind,
  //   MoveType.shoot,
  //   50,
  //   "Supernatural Scorer",
  //   "All teammates' shots don't lose as much power even when taken from afar"
  // ),
};
