import { MapView } from "@/components/MapView";
import { getImageUrl } from "@/config";
import { Link } from "react-router";

export function MainNav() {
  return (
    <MapView
      title="Inazuma TM Bus"
      imageSrc={getImageUrl("maps/IEGOCS/MainBackground.png")}
      width={320}
      height={216}
      markers={[
        <Link to="PresentInazuma">
          <image
            x={10}
            y={19}
            height={56}
            width={56}
            href={getImageUrl("maps/IEGOCS/0.png")}
          />
          <rect
            x={10}
            y={19}
            width={56}
            height={56}
            className="marker"
            cursor={"pointer"}
          />
        </Link>,
        <Link to="HolyRoadStadium">
          <image
            x={71}
            y={19}
            height={56}
            width={56}
            href={getImageUrl("maps/IEGOCS/1.png")}
          />
          <rect
            x={71}
            y={19}
            width={56}
            height={56}
            className="marker"
            cursor={"pointer"}
          />
        </Link>,
        <Link to="Sanctum">
          <image
            x={132}
            y={19}
            height={56}
            width={56}
            href={getImageUrl("maps/IEGOCS/2.png")}
          />
          <rect
            x={132}
            y={19}
            width={56}
            height={56}
            className="marker"
            cursor={"pointer"}
          />
        </Link>,
        <Link to="Okinawa">
          <image
            x={193}
            y={19}
            height={56}
            width={56}
            href={getImageUrl("maps/IEGOCS/3.png")}
          />
          <rect
            x={193}
            y={19}
            width={56}
            height={56}
            className="marker"
            cursor={"pointer"}
          />
        </Link>,
        <Link to="FFStadium">
          <image
            x={254}
            y={19}
            height={56}
            width={56}
            href={getImageUrl("maps/IEGOCS/4.png")}
          />
          <rect
            x={254}
            y={19}
            width={56}
            height={56}
            className="marker"
            cursor={"pointer"}
          />
        </Link>,
        <Link to="PastInazuma">
          <image
            x={10}
            y={80}
            height={56}
            width={56}
            href={getImageUrl("maps/IEGOCS/5.png")}
          />
          <rect
            x={10}
            y={80}
            width={56}
            height={56}
            className="marker"
            cursor={"pointer"}
          />
        </Link>,
        <Link to="Tonghana">
          <image
            x={71}
            y={80}
            height={56}
            width={56}
            href={getImageUrl("maps/IEGOCS/6.png")}
          />
          <rect
            x={71}
            y={80}
            width={56}
            height={56}
            className="marker"
            cursor={"pointer"}
          />
        </Link>,
        <Link to="SengokuJapan">
          <image
            x={132}
            y={80}
            height={56}
            width={56}
            href={getImageUrl("maps/IEGOCS/7.png")}
          />
          <rect
            x={132}
            y={80}
            width={56}
            height={56}
            className="marker"
            cursor={"pointer"}
          />
        </Link>,
        <Link to="MedievalFrance">
          <image
            x={193}
            y={80}
            height={56}
            width={56}
            href={getImageUrl("maps/IEGOCS/8.png")}
          />
          <rect
            x={193}
            y={80}
            width={56}
            height={56}
            className="marker"
            cursor={"pointer"}
          />
        </Link>,
        <Link to="ThreeKingdomsChina">
          <image
            x={254}
            y={80}
            height={56}
            width={56}
            href={getImageUrl("maps/IEGOCS/9.png")}
          />
          <rect
            x={254}
            y={80}
            width={56}
            height={56}
            className="marker"
            cursor={"pointer"}
          />
        </Link>,
        <Link to="EdoKyoto">
          <image
            x={10}
            y={141}
            height={56}
            width={56}
            href={getImageUrl("maps/IEGOCS/10.png")}
          />
          <rect
            x={10}
            y={141}
            width={56}
            height={56}
            className="marker"
            cursor={"pointer"}
          />
        </Link>,
        <Link to="Jurassic">
          <image
            x={71}
            y={141}
            height={56}
            width={56}
            href={getImageUrl("maps/IEGOCS/11.png")}
          />
          <rect
            x={71}
            y={141}
            width={56}
            height={56}
            className="marker"
            cursor={"pointer"}
          />
        </Link>,
        <Link to="Camelot">
          <image
            x={132}
            y={141}
            height={56}
            width={56}
            href={getImageUrl("maps/IEGOCS/12.png")}
          />
          <rect
            x={132}
            y={141}
            width={56}
            height={56}
            className="marker"
            cursor={"pointer"}
          />
        </Link>,
        <Link to="SanEldor">
          <image
            x={193}
            y={141}
            height={56}
            width={56}
            href={getImageUrl("maps/IEGOCS/13.png")}
          />
          <rect
            x={193}
            y={141}
            width={56}
            height={56}
            className="marker"
            cursor={"pointer"}
          />
        </Link>,
        <Link to="Dreamland">
          <image
            x={254}
            y={141}
            height={56}
            width={56}
            href={getImageUrl("maps/IEGOCS/14.png")}
          />
          <rect
            x={254}
            y={141}
            width={56}
            height={56}
            className="marker"
            cursor={"pointer"}
          />
        </Link>,
      ]}
    />
  );
}
